# Generated by Django 5.2.7 on 2025-10-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_carrito', '0001_initial'),
    ]

    operations = [
    ]
