# Generated by Django 5.2.7 on 2025-10-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_carrito', '0002_auto_20251028_1727'),
    ]

    operations = [
    ]
