# Generated by Django 5.2.7 on 2025-11-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_id_producto_producto_id_and_more'),
        ('ventas_carrito', '0005_add_payment_and_receipt_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito de Compras', 'verbose_name_plural': 'Carritos de Compras'},
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_agregado'),
        ),
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='fecha_agregado',
            new_name='fecha_adicion',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='pagoonline',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagoonline',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas_carrito.carrito'),
        ),
    ]
