# Generated by Django 5.2.7 on 2025-11-09 14:13

from django.db import migrations, models


def add_stripe_fields_safe(apps, schema_editor):
    """Agregar campos de Stripe solo si no existen"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar si existe stripe_session_id
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='pago_online' AND column_name='stripe_session_id'
        """)
        if not cursor.fetchone():
            try:
                cursor.execute("""
                    ALTER TABLE pago_online 
                    ADD COLUMN stripe_session_id VARCHAR(255) NULL
                """)
                # Agregar índice único después de crear la columna
                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS pago_online_stripe_session_id_unique 
                    ON pago_online(stripe_session_id) 
                    WHERE stripe_session_id IS NOT NULL
                """)
            except Exception as e:
                print(f"Warning: Could not add stripe_session_id: {e}")
        
        # Verificar si existe stripe_payment_intent_id
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='pago_online' AND column_name='stripe_payment_intent_id'
        """)
        if not cursor.fetchone():
            try:
                cursor.execute("""
                    ALTER TABLE pago_online 
                    ADD COLUMN stripe_payment_intent_id VARCHAR(255) NULL
                """)
            except Exception as e:
                print(f"Warning: Could not add stripe_payment_intent_id: {e}")


def reverse_add_stripe_fields(apps, schema_editor):
    """Revertir: remover campos de Stripe"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE pago_online DROP COLUMN IF EXISTS stripe_session_id")
            cursor.execute("ALTER TABLE pago_online DROP COLUMN IF EXISTS stripe_payment_intent_id")
        except Exception as e:
            print(f"Warning: Could not remove Stripe fields: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_carrito', '0006_alter_carrito_options_and_more'),
    ]

    operations = [
        # Agregar campos de forma segura (solo si no existen)
        migrations.RunPython(add_stripe_fields_safe, reverse_add_stripe_fields),
        
        # Registrar los campos en el estado de Django
        # Usamos SeparateDatabaseAndState para que Django sepa sobre los campos
        # pero no intente crearlos en la BD (ya los creamos en add_stripe_fields_safe)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacer nada en la BD, ya lo hicimos en add_stripe_fields_safe
            ],
            state_operations=[
                migrations.AddField(
                    model_name='pagoonline',
                    name='stripe_session_id',
                    field=models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                migrations.AddField(
                    model_name='pagoonline',
                    name='stripe_payment_intent_id',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
