# Generated by Django 5.2.7 on 2025-11-09 14:07

from django.db import migrations, models


def safe_migrate_producto(apps, schema_editor):
    """Migración segura que verifica existencia de columnas antes de modificarlas"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar y renombrar id_producto a id si es necesario
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='producto' AND column_name='id_producto'
        """)
        if cursor.fetchone():
            try:
                cursor.execute("ALTER TABLE producto RENAME COLUMN id_producto TO id")
            except Exception as e:
                print(f"Warning: Could not rename id_producto: {e}")
        
        # Remover campos solo si existen
        campos_a_remover = ['estado', 'fecha_actualizacion', 'fecha_creacion', 'precio_u_c', 'stock']
        for campo in campos_a_remover:
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='producto' AND column_name=%s
            """, [campo])
            if cursor.fetchone():
                try:
                    cursor.execute(f"ALTER TABLE producto DROP COLUMN {campo}")
                except Exception as e:
                    print(f"Warning: Could not remove {campo}: {e}")


def check_column_exists(cursor, table_name, column_name):
    """Verificar si una columna existe"""
    cursor.execute("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name=%s AND column_name=%s
    """, [table_name, column_name])
    return cursor.fetchone() is not None


def safe_add_fields(apps, schema_editor):
    """Agregar campos solo si no existen"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar y agregar precio si no existe
        if not check_column_exists(cursor, 'producto', 'precio_unitario'):
            try:
                cursor.execute("""
                    ALTER TABLE producto 
                    ADD COLUMN precio_unitario DECIMAL(10, 2) DEFAULT 0.0
                """)
            except Exception as e:
                print(f"Warning: Could not add precio_unitario: {e}")
        
        # Verificar y agregar precio_compra si no existe
        if not check_column_exists(cursor, 'producto', 'precio_unitario_compra'):
            try:
                cursor.execute("""
                    ALTER TABLE producto 
                    ADD COLUMN precio_unitario_compra DECIMAL(10, 2) DEFAULT 0.0
                """)
            except Exception as e:
                print(f"Warning: Could not add precio_unitario_compra: {e}")


def reverse_safe_migrate(apps, schema_editor):
    """Revertir migración"""
    pass  # No implementamos reverso por simplicidad


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_restructure_models'),
    ]

    operations = [
        # Ejecutar migración segura para renombrar y remover campos
        migrations.RunPython(safe_migrate_producto, reverse_safe_migrate),
        
        # Agregar nuevos campos de forma segura
        migrations.RunPython(safe_add_fields, reverse_safe_migrate),
        
        # Registrar los campos en el estado de Django
        # Usamos SeparateDatabaseAndState para que Django sepa sobre los campos
        # pero no intente crearlos en la BD (ya los creamos en safe_add_fields)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacer nada en la BD, ya lo hicimos en safe_add_fields
            ],
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='precio',
                    field=models.DecimalField(db_column='precio_unitario', decimal_places=2, default=0.0, max_digits=10),
                ),
                migrations.AddField(
                    model_name='producto',
                    name='precio_compra',
                    field=models.DecimalField(db_column='precio_unitario_compra', decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
    ]
